### ISSUE TITLE
player.ads is not a function when update npm

### ISSUE THREAD

**Issue by daviCalavera** [videojs/videojs-contrib-ads#311]
Hi guys,
I'm use this plugin with the google IMA plugin. This works fine, but i'm needed to update videojs and npm, when upgrade npm from versión 3.x to 5.x i have encountered the error: 
**'player.ads is not a function TypeError: player.ads is not a function'**
Reading another issues, I checked that i have not using any adblocker, but the issue persist.
When I donwgrade npm to 3.x the plugin works again.
Sorry my bad english. Thanks!

I import the packages using webpack.

**Comment by incompl** [comment]
Can you verify that videojs-contrib-ads is being included before videojs-ima?

**Comment by Kogoruhn** [comment]
I confirm. I have the same [problem](https://github.com/googleads/videojs-ima/issues/473) in my webpack-created budle.

**Comment by Kogoruhn** [comment]
@daviCalavera did you find a solution? If not yet, see link to my issue. Mayhap it helps.

**Comment by daviCalavera** [comment]
@incompl yes, confirmed. With npm 3 the same code works fine.
@Kogoruhn  not yet, I will check your link and comment any update.

**Comment by incompl** [comment]
@Kogoruhn Do you have a sense if anything in `videojs-contrib-ads` can be changed to support webpack better? I saw the `registerPlugin` part but it seems like that doesn't need to change in the contrib ads source.

**Comment by Kogoruhn** [comment]
Hi @incompl ! Thanks for your great work and support! 
Im new in JS, and I don't have enough knowledge. But I noticed that Webpack, because of its _harmony import_, starts ima and contrib-ads plugin _before_ `videojs` presence in `window` object. Therefore trigger of `video.js` not work (on `player.ima()` or `this.vjsPlayer.ads()` ) and as a result we have an error.
Maybe i'm wrong.

**Comment by incompl** [comment]
I believe the ideal solution is ultimately for videojs-contrib-ads to be imported by videojs-ima as a module dependency. I created an example of how that should work: 

https://github.com/videojs/videojs-contrib-ads/pull/312/files

I also updated the issue in videojs-ima with this information:

https://github.com/googleads/videojs-ima/issues/473

**Comment by incompl** [comment]
I posted more information here: https://github.com/videojs/videojs-contrib-ads/issues/314

**Comment by incompl** [comment]
This issue is pretty stale and there are several similar ones so I'm closing it, but feel free to reach out if you're still having issues!
