### ISSUE TITLE
Mutliple "Uncaught TypeError: player.$ is not a function" in IMA plugin

### ISSUE THREAD

**Issue by shawnbuso** [videojs/videojs-contrib-ads#139]
I'm trying to update the IMA plugin for video.js 5.0. I'm using videojs-contrib-ads 3.1.2. When I start my player, the pre-roll and content play at the same time, with multiple logs of "Uncaught TypeError: player.$ is not a function". After the pre-roll finishes the content plays on and mid-rolls play fine, pausing the content as expected. It looks like the ads plugin for some reason is firing adtimeout immediately after firing adsready, so it plays content (assuming ads have timed out) before I get a chance to tell it that the pre-roll is ready.

Example page: http://shawnbuso.github.io/videojs-ima/examples/simple/

**Comment by shawnbuso** [comment]
D'oh should have checked the package.json - this works fine with vjs 5.3, I was using 5.0.

**Comment by gkatsev** [comment]
I think the issue is that you're using a too-old version of videojs 5.x. In [5.2](https://github.com/videojs/video.js/blob/master/CHANGELOG.md#520-2015-11-10) we added a bunch of DOM helpers. The latest release is currently https://github.com/videojs/video.js/releases/tag/v5.4.4.
You could also try using [v3.1.0](https://github.com/videojs/videojs-contrib-ads/tree/v3.1.0) which is before this plugin picked up the changes to use the new DOM helpers.
Closing as there probably won't be any more changes required for this, but if there are more issues or you have more questions, please comment and we can reopen if necessary.

**Comment by gkatsev** [comment]
Oh, missed your comment. Yeah, version mismatch :)
Glad you figured it out.

**Comment by AravindG7** [comment]
Hi Gray Katesevan
Since a month I be associate and working in VIDEOJS related stuff. I am trying to play ads like (pre-roll ads once, and mid-roll multiple times and post-roll once) using VIDEOJS with VAST & VPAID ads support. i stuck with a very critical error is written below,  
Error: 
Type error: player vast is not a function  
 
I am using firebug web-debugger tool in firefox web browser.
I didn’t find any solutions please help in this sensitive issue kindly.

I have many questions regarding VIDEOJS, please replay me ASAP.
 
How can i play multiple times mid-roll ads in my videojs player ?
Is VIDEOJS supports multiple mid-roll play Ads using VAST?

please share any contact details like (skypeid, email) therefor i could contact with you very easily, i  am obliged to you.
 
My Contact Details:
aravind@muvi.com
aravind_g7 (skype id)
waiting for your response.
